# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: DevOps Academy 2.0 - Review Exercises

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # initiate:
  #   #TODO parse a file to review job
  #   # command from shell, we want to be able to get it within devOpsAcademy
  #   runs-on: ubuntu-latest
  #   outputs:
  #     listdir: ${{ steps.initial.outputs.listdir }}
  #   steps:
  #     - id: initial
  #       run: |
  #         echo "listdir=$(ls -R)" >> $GITHUB_OUTPUT

  review-exercise1:
    runs-on: ubuntu-latest
    # needs: initiate
    steps:
    - name: Review Exercises 1 
      uses: devopsacademyau/academy2/exercise1@denis
      # with:
      #   listdir: ${{ needs.initiate.outputs.listdir }}
      #   ref: v0
     