# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: DevOps Academy 2.0 - Review Exercises

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Review Exercise 1
      uses: devopsacademyau/academy2@v1
      # with:
        # repository: octocat/my-private-repo
        #ref: v0
        # token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        # path: ./.github/actions/my-private-repo
      #with:
        #owner: studentA
        #github_token: ${{ secrets.SVC_GITHUB_DEVOPS }}
        # ref: tag, branch or commit 