# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: DevOps Academy 2.0 - Review Exercises

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  initialize:
    runs-on: ubuntu-latest
    outputs:
      listdir: ${{ steps.initial.outputs.listdir }}
    steps:
      - id: initial
        run: |
          echo "listdir=$(find .)"
          echo "listdir=$(find .)" >> $GITHUB_OUTPUT

  review:
    runs-on: ubuntu-latest
    needs: initialize
    steps:
    - name: Review Exercise 1
      uses: devopsacademyau/academy2/exercise1@dev
      with:
        ref: v0
        listdir: ${{ steps.initial.outputs.listdir }}
     